name: rpmbuild
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
      - '[0-9].[0-9]RC'
      - '[0-9].[0-9][0-9]RC'

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  rpmbuild:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    continue-on-error: ${{ matrix.config.continue-on-error == 'true' }}
    strategy:
      matrix:
        config:
          - {arch: 'arm64'}
          - {arch: 'amd64'}
    runs-on: ${{ matrix.config.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    container: fedora:latest
    steps:
      - name: Install fedpkg
        run: dnf -y install fedpkg
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: Silo
      - name: Prepare rpmbuild
        run: |
          mkdir Silo.rpm
          tar -cvzf Silo-9999.tar.gz Silo/
          cp Silo-9999.tar.gz Silo/.github/workflows/Silo.spec Silo.rpm
      - name: Install build deps
        working-directory: Silo.rpm
        run: |
          dnf -y builddep Silo.spec
      - name: Build rpm
        working-directory: Silo.rpm
        run: |
          fedpkg --verbose --debug local

